(function(){function s(b){return Object.keys(b)}function r(b){return Array.isArray(b)}function t(b){return"function"==typeof b}function y(b){for(var d=s(b),a=-1,c=d.length,e=Array(c);++a<c;)e[a]=b[d[a]];return e}function w(b,d){for(var a=-1,c=b.length;++a<c&&!1!==d(b[a],a,b););return b}function z(b,d,a){a=a||s(b);for(var c=-1,e=a.length;++c<e;){var f=a[c];if(!1===d(b[f],f,b))break}return b}function v(b,d){for(var a=-1;++a<b;)d(a)}function ea(b,d){for(var a=b.length,c=-1;++c<a;)if(!d(b[c]))return!1;
return!0}function C(b){for(var d=b.length,a=-1,c=Array(d);++a<d;)c[a]=b[d];return c}function R(b){for(var d=s(b),a=d.length,c=-1,e={};++c<a;){var f=d[c];e[f]=b[f]}return e}function S(b,d){for(var a=-1,c=b.length,e=Array(c);++a<c;)e[a]=(b[a]||{})[d];return e}function p(b){var d=!1;return function(){if(d)throw Error("Callback was already called.");d=!0;b.apply(B,arguments)}}function D(b,d,a,c){function e(b,c){if(!h){if(b)return h=!0,a(b);if(!1===c)return h=!0,a();++g>=f&&(h=!0,a())}}a=a||function(){};
var f=0,g=0,h=!1,k=c?d.bind(c):d;d=function(a){k(a,p(e))};if(r(b)){f=b.length;if(!f)return a();w(b,d)}else{c=s(b);f=c.length;if(!f)return a();z(b,d,c)}}function E(b,d,a,c){function e(b,c){if(!h){if(b)return h=!0,a(b);if(!1===c||++g>=f)return h=!0,a();l()}}a=a||function(){};var f=0,g=0,h=!1,k=c?d.bind(c):d,l;if(r(b)){f=b.length;if(!f)return a();l=function(){k(b[g],p(e))}}else{var m=s(b),f=m.length;if(!f)return a();l=function(){k(b[m[g]],p(e))}}l()}function T(b,d,a,c,e){function f(a,b){if(!l){if(a)return l=
!0,c(a);if(!1===b||++h>=g)return l=!0,c();h>=k+d&&(k=h,n())}}c=c||function(){};var g=0,h=0,k=0,l=!1,m=e?a.bind(e):a,n;if(r(b)){g=b.length;if(!g)return c();n=function(){v(d,function(a){k+a>=g||m(b[k+a],p(f))})}}else{var q=s(b),g=q.length;if(!g)return c();n=function(){v(d,function(a){k+a>=g||m(b[q[k+a]],p(f))})}}n()}function V(b,d,a,c){function e(b){return function(c,e){if(!l){g[b]=e;if(c)return l=!0,a(c);++k>=f&&(l=!0,a(null,g))}}}a=a||function(){};var f=0,g=[],h=0,k=0,l=!1,m=c?d.bind(c):d;d=function(a){m(a,
p(e(h++)))};if(r(b)){f=b.length;if(!f)return a(null,g);w(b,d)}else{c=s(b);f=c.length;if(!f)return a(null,g);z(b,d,c)}}function W(b,d,a,c){function e(b){return function(c,e){if(!k){g[b]=e;if(c)return k=!0,a(c);if(++h>=f)return k=!0,a(null,g);m()}}}a=a||function(){};var f=0,g=[],h=0,k=!1,l=c?d.bind(c):d,m;if(r(b)){f=b.length;if(!f)return a(null,g);m=function(){l(b[h],p(e(h)))}}else{var n=s(b),f=n.length;if(!f)return a(null,g);m=function(){l(b[n[h]],p(e(h)))}}m()}function X(b,d,a,c,e){function f(a){return function(b,
e){if(!m){h[a]=e;if(b)return m=!0,c(b);if(++k>=g)return m=!0,c(null,h);k>=l+d&&(l=k,q())}}}c=c||function(){};var g=0,h=[],k=0,l=0,m=!1,n=e?a.bind(e):a,q;if(r(b)){g=b.length;if(!g)return c(null,h);q=function(){v(d,function(a){l+a>=g||(a=l+a,n(b[a],p(f(a))))})}}else{var u=s(b),g=u.length;if(!g)return c(null,h);q=function(){v(d,function(a){l+a>=g||(a=l+a,n(b[u[a]],p(f(a))))})}}q()}function F(b){function d(a,b,g,d){g=c(a,g);G(a,b,g,d)}function a(a,b,g,d,k){d=c(a,d);H(a,b,g,d,k)}function c(a,b){return function(c){b(r(a)?
c:y(c))}}switch(b){case "series":return d;case "limit":return a;default:return function(a,b,g,d){g=c(a,g);I(a,b,g,d)}}}function J(b,d,a,c,e){a=a||function(){};var f=0,g=0,h=!1,k=function(){function b(c){return function(b){if(!h){if(!b)return h=!0,a(c);++g>=f&&(h=!0,a())}}}function c(b){return function(c){if(!h){if(c)return h=!0,a(b);++g>=f&&(h=!0,a())}}}return e?b:c}(),l=c?d.bind(c):d;d=function(a){l(a,p(k(a)))};if(r(b)){f=b.length;if(!f)return a();w(b,d)}else{f=s(b).length;if(!f)return a();z(b,d)}}
function K(b,d,a,c,e){a=a||function(){};var f=0,g=0,h=!1,k=function(){function b(c){return function(b){if(!h){if(!b)return h=!0,a(c);if(++g>=f)return h=!0,a();m()}}}function c(b){return function(c){if(!h){if(c)return h=!0,a(b);if(++g>=f)return h=!0,a();m()}}}return e?b:c}(),l=c?d.bind(c):d,m;if(r(b)){f=b.length;if(!f)return a([]);m=function(){var a=b[g];l(a,p(k(a)))}}else{var n=s(b),f=n.length;if(!f)return a({});m=function(){var a=b[n[g]];l(a,p(k(a)))}}m()}function L(b,d,a,c,e,f){c=c||function(){};
var g=0,h=0,k=0,l=!1,m=function(){function a(b){return function(a){if(!l){if(!a)return l=!0,c(b);if(++h>=g)return c();h>=k+d&&(k=h,q())}}}function b(a){return function(b){if(!l){if(b)return l=!0,c(a);if(++h>=g)return c();h>=k+d&&(k=h,q())}}}return f?a:b}(),n=e?a.bind(e):a,q;if(r(b)){g=b.length;if(!g)return c();q=function(){v(d,function(a){k+a>=g||(a=b[k+a],n(a,p(m(a))))})}}else{var u=s(b),g=u.length;if(!g)return c();q=function(){v(d,function(a){k+a>=g||(a=b[u[k+a]],n(a,p(m(a))))})}}q()}function I(b,
d,a,c,e){a=a||function(){};var f=0,g=r(b),h={},k=0,l=function(){function b(c,d){return function(b){b||(h[c+""]=d);++k>=f&&a(g?y(h):h)}}function c(b,d){return function(c){c&&(h[b+""]=d);++k>=f&&a(g?y(h):h)}}return e?b:c}(),m=c?d.bind(c):d;d=function(a,b){m(a,p(l(b,a)))};if(g){f=b.length;if(!f)return a([]);w(b,d)}else{f=s(b).length;if(!f)return a({});z(b,d)}}function G(b,d,a,c,e){a=a||function(){};var f=0,g=r(b),h={},k=0,l=function(){function b(c,d){return function(b){b||(h[c+""]=d);if(++k>=f)return a(g?
y(h):h);n()}}function c(b,d){return function(c){c&&(h[b+""]=d);if(++k>=f)return a(g?y(h):h);n()}}return e?b:c}(),m=c?d.bind(c):d,n;if(g){f=b.length;if(!f)return a([]);n=function(){var a=b[k];m(a,p(l(k,a)))}}else{var q=s(b),f=q.length;if(!f)return a({});n=function(){var a=q[k],c=b[a];m(c,p(l(a,c)))}}n()}function H(b,d,a,c,e,f){c=c||function(){};var g=0,h=r(b),k={},l=0,m=0,n=function(){function a(b,e){return function(a){a||(k[b+""]=e);if(++l>=g)return c(h?y(k):k);l>=m+d&&(m=l,u())}}function b(a,e){return function(b){b&&
(k[a+""]=e);if(++l>=g)return c(h?y(k):k);l>=m+d&&(m=l,u())}}return f?a:b}(),q=e?a.bind(e):a,u;if(h){g=b.length;if(!g)return c([]);u=function(){v(d,function(a){if(!(m+a>=g)){a=m+a;var c=b[a];q(c,p(n(a,c)))}})}}else{var U=s(b),g=U.length;if(!g)return c({});u=function(){v(d,function(a){if(!(m+a>=g)){a=U[m+a];var c=b[a];q(c,p(n(a,c)))}})}}u()}function M(b,d,a,c,e){function f(a,b){if(!k){if(a)return k=!0,c(a);if(++h>=g)return k=!0,c(null,b);m(b)}}c=c||function(){};var g=0,h=0,k=!1,l=e?a.bind(e):a,m;if(r(b)){g=
b.length;if(!g)return c(null,d);m=function(a){l(a,b[h],p(f))}}else{var n=s(b),g=n.length;if(!g)return c(null,d);m=function(a){l(a,b[n[h]],p(f))}}m(d)}function Y(b,d,a,c){function e(b,c){if(!l){if(b)return l=!0,a(b);if(!1===c)return l=!0,a(null,g?C(h):R(h));++k>=f&&(l=!0,a(null,h))}}a=a||function(){};var f=0,g=r(b),h=g?[]:{},k=0,l=!1,m=c?d.bind(c):d;d=function(a,b){m(h,a,b,p(e))};if(g){f=b.length;if(!f)return a(null,h);w(b,d)}else{c=s(b);f=c.length;if(!f)return a(null,h);z(b,d,c)}}function Z(b,d,a,
c){function e(b,c){if(!l){if(b)return l=!0,a(b);if(!1===c||++k>=f)return l=!0,a(null,h);n()}}a=a||function(){};var f=0,g=r(b),h=g?[]:{},k=0,l=!1,m=c?d.bind(c):d,n;if(g){f=b.length;if(!f)return a(null,h);n=function(){m(h,b[k],k,p(e))}}else{var q=s(b),f=q.length;if(!f)return a(null,h);n=function(){var a=q[k];m(h,b[a],a,p(e))}}n()}function $(b,d,a,c,e){function f(a,b){if(!n){if(a)return n=!0,c(a);if(!1===b)return n=!0,c(null,h?C(k):R(k));if(++l>=g)return n=!0,c(null,k);l>=m+d&&(m=l,u())}}c=c||function(){};
var g=0,h=r(b),k=h?[]:{},l=0,m=0,n=!1,q=e?a.bind(e):a,u;if(h){g=b.length;if(!g)return c(null,k);u=function(){v(d,function(a){m+a>=g||(a=m+a,q(k,b[a],a,p(f)))})}}else{var t=s(b),g=t.length;if(!g)return c(null,k);u=function(){v(d,function(a){m+a>=g||(a=t[m+a],q(k,b[a],a,p(f)))})}}u()}function N(b){function d(a,b,d,k){b=c(b,k);W(a,b,e(d))}function a(a,b,d,k,l){d=c(d,l);X(a,b,d,e(k))}function c(a,b){var c=b?a.bind(b):a;return function(a,b){c(a,function(c,d){if(c)return b(c);b(null,{item:a,criteria:d})})}}
function e(a){return function(b,c){if(b)return a(b);var d=c.sort(function(a,b){return b.criteria<a.criteria});a(null,S(d,"item"))}}switch(b){case "series":return d;case "limit":return a;default:return function(a,b,d,k){b=c(b,k);V(a,b,e(d))}}}function O(b){return function(d,a,c,e){(b?a.bind(b):a)(function(a,b){if(a)return e(a);d[c]=b;e()})}}function aa(){var b=arguments;return function(){var d=this,a=Array.prototype.slice.call(arguments),c=a.pop();M(b,a,function(a,b,c){a.push(function(a){var b=Array.prototype.slice.call(arguments,
1);c(a,b)});b.apply(d,a)},function(a,b){b=r(b)?b:[b];b.unshift(a);c.apply(d,b)})}}function ba(b){var d="series"===b?E:D;return function(a){var b=this,e=Array.prototype.slice.call(arguments,1),f=e.pop()||function(){};d(a,function(a,d){a.apply(b,e.concat(d))},f)}}function ca(b,d,a){function c(a,b,c){e.started=!0;var d=r(a)?a:[a];if(!a||!d.length)return x(function(){t(e.drain)&&e.drain()});c=t(c)?c:null;w(d,function(a){e.tasks.push({task:a,priority:b,callback:c});e.tasks=e.tasks.sort(function(a,b){return b.priority<
a.priority});t(e.saturated)&&e.length()>=e.concurrency&&e.saturated();x(e.process)})}var e={tasks:[],concurrency:d||1,saturated:null,empty:null,drain:null,started:!1,paused:!1,push:function(a,b,d){c(a,b,d)},kill:function(){e.drain=null;e.tasks=[]},process:function(){function a(){f--;b.callback&&b.callback.apply(b,arguments);t(e.drain)&&e.idle()&&e.drain();e.process()}if(!(e.paused||f>=e.concurrency||0===e.length())){var b=e.tasks.shift();t(e.empty)&&e.length()&&e.empty();f++;(e._thisArg?e._worker.bind(e._thisArg):
e._worker)(b.task,p(a))}},length:function(){return e.tasks.length},runnning:function(){return f},idle:function(){return 0===e.length()+f},pause:function(){e.paused=!0},resume:function(){!1!==e.paused&&(e.paused=!1,v(e.concurrency,function(){P.setImmediate(e.process)}))},_worker:b,_thisArg:a},f=0;return e}function da(b,d,a,c){function e(c){return function(d,n){if(!g){f[c]=n;if(d)return g=!0,a(d);if(++h>=b)return g=!0,a(null,f);k(h,p(e(h)))}}}a=a||function(){};var f=[];if(1>b)return a(null,f);var g=
!1,h=0,k=c?d.bind(c):d;k(h,p(e(h)))}function Q(b){function d(a){var c=Array.prototype.slice.call(arguments,1);console&&(a?console.error&&console.error(a):console[b]&&w(c,console[b]))}return function(a){var b=Array.prototype.slice.call(arguments,1);b.push(d);a.apply(null,b)}}var B=this,fa=B&&B.async,A,x;(function(){process&&process.nextTick?(A=process.nextTick,x=t(setImmediate)?function(b){setImmediate(b)}:A):x=A=t(setImmediate)?function(b){setImmediate(b)}:function(b){setTimeout(b,0)}})();var P={each:D,
eachSeries:E,eachLimit:T,forEach:D,forEachSeries:E,forEachLimit:T,map:V,mapSeries:W,mapLimit:X,filter:F(),filterSeries:F("series"),filterLimit:F("limit"),reject:function(b,d,a,c){I(b,d,a,c,!0)},rejectSeries:function(b,d,a,c){G(b,d,a,c,!0)},rejectLimit:function(b,d,a,c,e){H(b,d,a,c,e,!0)},detect:J,detectSeries:K,detectLimit:L,pick:I,pickSeries:G,pickLimit:H,reduce:M,reduceRight:function(b,d,a,c,e){function f(a,b){if(!k){if(a)return k=!0,c(a);if(++h>=g)return k=!0,c(null,b);m(b)}}c=c||function(){};
var g=0,h=0,k=!1,l=e?a.bind(e):a,m;if(r(b)){g=b.length;if(!g)return c(null,d);m=function(a){l(a,b[g-h-1],p(f))}}else{var n=s(b),g=n.length;if(!g)return c(null,d);m=function(a){l(a,b[n[g-h-1]],p(f))}}m(d)},transform:Y,transformSeries:Z,transformLimit:$,sortBy:N(),sortBySeries:N("series"),sortByLimit:N("limit"),some:function(b,d,a,c){J(b,d,function(b){a(!!b)},c)},someSeries:function(b,d,a,c){K(b,d,function(b){a(!!b)},c)},someLimit:function(b,d,a,c,e){L(b,d,a,function(a){c(!!a)},e)},every:function(b,
d,a,c){J(b,d,function(b){a(!b)},c,!0)},everySeries:function(b,d,a,c){K(b,d,function(b){a(!b)},c,!0)},everyLimit:function(b,d,a,c,e){L(b,d,a,function(a){c(!a)},e,!0)},concat:function(b,d,a,c){function e(b,c){if(!k){if(b)return k=!0,a(b);r(c)&&c.length&&Array.prototype.push.apply(g,c);++h>=f&&(k=!0,a(null,g))}}a=a||function(){};var f=0,g=[],h=0,k=!1,l=c?d.bind(c):d;d=function(a){l(a,p(e))};if(r(b)){f=b.length;if(!f)return a(null,g);w(b,d)}else{c=s(b);f=c.length;if(!f)return a(null,g);z(b,d,c)}},concatSeries:function(b,
d,a,c){function e(b,c){if(!l){if(b)return l=!0,a(b);r(c)&&c.length&&Array.prototype.push.apply(h,c);if(++k>=f)return l=!0,a(null,h);n()}}a=a||function(){};var f=0,g=r(b),h=[],k=0,l=!1,m=c?d.bind(c):d,n;if(g)f=b.length,n=function(){m(b[k],p(e))};else{var q=s(b),f=q.length;n=function(){m(b[q[k]],p(e))}}if(!f)return a(null,h);n()},concatLimit:function(b,d,a,c,e){function f(a,b){if(!n){if(a)return n=!0,c(a);r(b)&&b.length&&Array.prototype.push.apply(k,b);if(++l>=g)return n=!0,c(null,k);l>=m+d&&(m=l,u())}}
c=c||function(){};var g=0,h=r(b),k=[],l=0,m=0,n=!1,q=e?a.bind(e):a,u;if(h){g=b.length;if(!g)return c(null,k);u=function(){v(d,function(a){m+a>=g||q(b[m+a],p(f))})}}else{var t=s(b),g=t.length;if(!g)return c(null,k);u=function(){v(d,function(a){m+a>=g||q(b[t[m+a]],p(f))})}}u()},parallel:function(b,d,a){var c=O(a);Y(b,c,d,a)},series:function(b,d,a){var c=O(a);Z(b,c,d,a)},parallelLimit:function(b,d,a,c){var e=O(c);$(b,d,e,a,c)},waterfall:function(b,d,a){M(b,{},function(b,d,f){function g(a){if(a)return f(a);
var d=Array.prototype.slice.call(arguments,1);b.args=d;f(null,b)}var h=b.args||[];h&&h.length?(h.push(g),d.apply(a,h)):(a?d.bind(a):d)(g)},function(b,e){if(b)return d(b);var f=e.args||[];f.unshift(b);d.apply(a,f)})},whilst:function(b,d,a,c){function e(){b()?f(function(b){if(b)return a(b);e()}):a()}a=a||function(){};var f=c?d.bind(c):d;e()},doWhilst:function(b,d,a,c){function e(){f(function(b){if(b)return a(b);var f=Array.prototype.slice.call(arguments,1);d.apply(c,f)?e():a()})}a=a||function(){};var f=
c?b.bind(c):b;e()},until:function(b,d,a,c){function e(){b()?a():f(function(b){if(b)return a(b);e()})}a=a||function(){};var f=c?d.bind(c):d;e()},doUntil:function(b,d,a,c){function e(){f(function(b){if(b)return a(b);var f=Array.prototype.slice.call(arguments,1);d.apply(c,f)?a():e()})}a=a||function(){};var f=c?b.bind(c):b;e()},forever:function(b,d,a){function c(){e(function(a){if(a)return d(a);c()})}d=d||function(){};var e=a?b.bind(a):b;c()},compose:function(){return aa.apply(null,Array.prototype.reverse.call(arguments))},
seq:aa,applyEach:ba(),applyEachSeries:ba("series"),queue:function(b,d,a){function c(a,b,c){e.started=!0;var d=r(a)?a:[a];if(!a||!d.length)return x(function(){t(e.drain)&&e.drain()});b=t(b)?b:null;w(d,function(a){a={task:a,callback:b};c?e.tasks.unshift(a):e.tasks.push(a);t(e.saturated)&&e.length()>=e.concurrency&&e.saturated();x(e.process)})}var e=ca(b,d,a);e.unshift=function(a,b){c(a,b,!0)};e.push=function(a,b){c(a,b)};return e},priorityQueue:ca,cargo:function(b,d){var a={tasks:[],payload:d,saturated:null,
empty:null,drain:null,drained:!0,push:function(b,c){b=r(b)?b:[b];c=t(c)?c:null;w(b,function(b){a.tasks.push({data:b,callback:c});a.drained=!1;t(a.saturated)&&a.length()===a.payload&&a.saturated()});x(a.process)},process:function(){if(!c)if(a.length()){var e="number"==typeof a.payload?a.tasks.splice(0,d):a.tasks,f=S(e,"data");t(a.empty)&&a.empty();c=!0;b(f,function(){c=!1;var b=arguments;w(e,function(a){a.callback&&a.callback.apply(null,b)});a.process()})}else t(a.drain)&&!a.drained&&a.drain(),a.drained=
!0},length:function(){return a.tasks.length},runnning:function(){return c}},c=!1;return a},auto:function(b,d){function a(a){g.unshift(a)}function c(){f--;w(g.slice(0),function(a){a()})}d=p(d)||function(){};var e=s(b),f=e.length;if(!f)return d();var g=[],h={};a(function(){f||d(null,h)});z(b,function(b,e){function f(a){var b=Array.prototype.slice.call(arguments,1);1>=b.length&&(b=b[0]);if(a){var g=C(h);g[e]=b;return d(a,g)}h[e]=b;x(c)}function n(){return!h.hasOwnProperty(e)&&ea(s,function(a){return h.hasOwnProperty(a)})}
function q(){if(n()){var a;a:{a=-1;for(var b=g.length;++a<b;)if(g[a]===q)break a;a=-1}0<=a&&g.splice(a,1);t(f,h)}}b=r(b)?b:[b];var p=b.length,s=b.slice(0,p-1),t=b[p-1];if(n())return t(f,h);a(q)},e)},retry:function(b,d,a){function c(c,f){a=c||a||function(){};var g,h;da(b,function(a,c){d(function(d,e){g=d;h=e;if(!d)return c(!0);c(d&&a===b-1)},f)},function(){a(g,h)})}t(b)&&(a=d,d=b,b=5);b=parseInt(b,10)||5;return t(a)?c():c},iterator:function(b){function d(c){var e=function(){a&&b[c].apply(null,arguments);
return e.next()};e.next=function(){return c<a-1?d(c+1):null};return e}var a=0,c=0;if(r(b))a=b.length;else var e=s(b),a=e.length,c=e[c];return d(c)},apply:function(b){var d=Array.prototype.slice.call(arguments,1);return function(){b.apply(null,Array.prototype.concat.apply(d,arguments))}},nextTick:A,setImmediate:x,times:function(b,d,a,c){function e(c){return function(d,e){if(!g){f[c]=e;if(d)return g=!0,a(d);++h>=b&&(g=!0,a(null,f))}}}a=a||function(){};var f=[];if(1>b)return a(null,f);var g=!1,h=0,k=
c?d.bind(c):d;v(b,function(a){k(a,p(e(a)))})},timesSeries:da,timesLimit:function(b,d,a,c,e){function f(a){return function(e,f){if(!h){g[a]=f;if(e)return h=!0,c(e);if(++k>=b)return h=!0,c(null,g);k>=l+d&&(l=k,n())}}}c=c||function(){};var g=[];if(1>b)return c(null,g);var h=!1,k=0,l=0,m=e?a.bind(e):a,n=function(){v(d,function(a){l+a>=b||(a=l+a,m(a,p(f(a))))})};n()},memoize:function(b,d,a){d=d||function(a){return a};var c={},e={},f=function(){function f(){c[l]=arguments;var b=e[l];delete e[l];for(var d=
-1,g=b.length;++d<g;)b[d].apply(a,arguments)}var h=Array.prototype.slice.call(arguments),k=h.pop(),l=d.apply(null,h);if(c.hasOwnProperty(l))A(function(){k.apply(a,c[l])});else{if(e.hasOwnProperty(l))return e[l].push(k);e[l]=[k];h.push(f);b.apply(a,h)}};f.memo=c;f.unmemoized=b;return f},unmemoize:function(b){return function(){return(b.unmemoized||b).apply(null,arguments)}},log:Q("log"),dir:Q("dir"),createLogger:Q,noConflict:function(){B.async=fa;return P}};module&&(module.exports=P)})();
